### ISSUE TITLE
SPF format YouTube HTML5 Roadmap- HELP! :))

### ISSUE THREAD

**Issue by kraftyman** [mediafront/osmplayer#9]
Hi,

I was very glad to see a new September release and a github presence. I am preparing a .com built around your OSM player but as a matter of due diligence I am currently investigating a roadmap for the day YouTube moves to HTML5 and flash no longer works.

I have modified the OSM scripts extensively, the code is very pretty, but I am facing the following questions & I sincerely hope some guidance/advice/reassurance can be offered :))

A. the SPF format I am using works fine with the <location> pointing to the canonical http://www.youtube.com/watch?v=VIDEOID format. What happens if this is soon broadcast in HTML5 or however the deprecation of YT vis a vis flash will likely go down?

I traced the code and it seems to be going the "drupal" route which I did not expect. The code while elegant is highly abstracted so understanding is somewhat of a challenge.

Further I signed up for the YouTube HTML5 beta but that apparently does not carry over to the OSM player... worth a try at least.. :))

I tried using the youtube /embed/videoid format but OSM did NOT like that and just started jumping through my playlist showing thumbs in an infinite loop. Fiddler was showing 200 OK YT responses but the contents of the response were for the YT player, which makes sense but my dilemma is:

How can I perform due diligence that HTML5 format will be recognized when YT makes the switch, i.e. comes out of beta and well... "goes for it..?"

Part of my concern is that I directly modified the JQUERY.OSMPLAYER script so upgrading will require some elbow grease & testing.

Finally if possible I'd love to submit our site when we go beta to your site as a showcase of what OSM can do if that is something you entertain.

Thanks again for a great video player.

Cary Abramoff CTO
CALB, LLC

**Comment by kraftyman** [comment]
PS- I forgot to add I also tried adding the ?html5=1 parameter to the youtube /watch?v= url format and again, error city with the playlist going in a lightspeed infinite loop as it would not accept that format a'tall! :))

**Comment by travist** [comment]
Cary,

First of all, thank you so much for your efforts and attention you have spent with this player.  I have some big plans to eventually update the youtube portion of the site to use their new HTML5 media player, but I have just not had much time lately to take on this feat.  It sounds to me like you have already made significant progress.  Do you have your code in a place where you could create a pull request that I can take a look at of the work you have done thus far?  If so, I will do what I can to update the codebase to reflect those changes.

Also, I am currently working on a new minimalist HTML5 media player which uses plugins to add extra features.  I have already started this work if you want to see where it is going at http://github.com/travist/minplayer.  My goal with that project is basically a ground up rework of the OSMPlayer, but instead using a new minimalist "core" player, and then using plugins I can try to get it up to par with the OSMPlayer.  As you noticed the OSMPlayer is kind of a beast to work with since it has a lot of components that all communicate with one another.

There is still a lot of work to do, but the architecture of the minPlayer is better than OSM since it uses dependency injection instead of event dispatching to handle the events.  This makes it significantly more performant.  More great stuff to come!

Thanks again for your efforts.

Travis.

**Comment by kraftyman** [comment]
Hi Travis,

I'm sorry I did not realize when I replied to the email I received from github (first time :))) that it would end up being public. My bad. I had to change the credentials for our demo I posted so that it would not be publicly available.

You can just contact me offline at caryabramoff@yahoo.com and I'll be happy to reply with new credentials.

Thanks sir,

Cary

**Comment by travist** [comment]
I deleted the previous comments.  Will respond to you via email.
